concept-sharing-sem1/Controllers/AdministratorController.cs
using concept_sharing_sem1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using concept_sharing_sem1.ViewModels;
using System.Data.SqlClient;

namespace concept_sharing_sem1.Controllers
{
    public class AdministratorController : Controller
    {
        // GET: Administrator
        private Connection db = new Connection();

        [Authorize(Roles = "1")]
        public ActionResult Index(string sortOrder, string searchString)
        {
            var UserList = db.Users.Include(x => x.Role).ToList();

            ViewBag.UserNameSort = String.IsNullOrEmpty(sortOrder) ? "Username" : "";
            ViewBag.EmailSort = String.IsNullOrEmpty(sortOrder) ? "Email" : "";
            ViewBag.RoleSort = String.IsNullOrEmpty(sortOrder) ? "Role" : "";
            

            if (!String.IsNullOrEmpty(searchString))
            {                
                UserList = db.Users.Include(x => x.Role).Where(x => x.Username.Contains(searchString)).ToList();
            }

            switch (sortOrder)
            {
                case "Username":
                    UserList = db.Users.Include(x => x.Role).OrderByDescending(x => x.Username).ToList();
                    break;
                case "Role":
                    //role virker ikke, tror det er pga forreign key selvom jeg .includer den
                    UserList = db.Users.Include(x => x.Role).OrderByDescending(x => x.Role).ToList();
                    break;

                case "Email":
                    UserList = db.Users.Include(x => x.Role).OrderByDescending(x => x.Email).ToList();
                    break;
                default:
                    //UserList = db.Users.Include(x => x.Role).OrderByDescending(x => x.Username).ToList();
                    //kan ikke få default til at virke da den overksriver de andre
                    break;
            }
                   
            
            return View(UserList);
        }
        public ActionResult DeleteUser(FormCollection fcNotUsed, int id = 0)
        {
            User user= db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteConcept(FormCollection fcNotUsed, int id = 0)
        {
            Concept delconcept = db.Concepts.Find(id);
            Source delsource = db.Sources.Find(id);
            Subject delsubject = db.Subjects.Find(id);
            if (delconcept== null)
            {
                return HttpNotFound();
            }
            db.Sources.Remove(delsource);
            db.Subjects.Remove(delsubject);
            db.Concepts.Remove(delconcept);
            db.SaveChanges();
    

            return RedirectToAction("AdminConcept");
        }


        public ActionResult Create()
        {


            return View();
        }
        public ActionResult AdminConcept(string ConceptSearch)
        {

            var ConceptList = db.Concepts.Include(x => x.subject).ToList();

           


            if (!String.IsNullOrEmpty(ConceptSearch))
            {
                ConceptList = db.Concepts.Include(x => x.subject).Where(x => x.subject.Title.Contains(ConceptSearch)).ToList();
            }

      

            return View(ConceptList);
        }
        //public ViewResult gotoconcept()
        //{
        //    return RedirectToAction();
        //}
    }
}

concept-sharing-sem1/Controllers/StudentController.cs
using concept_sharing_sem1.Models;
using concept_sharing_sem1.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

using static concept_sharing_sem1.ViewModels.ConceptViewModel;
using System.Web.UI.WebControls;
using System.Net;

namespace concept_sharing_sem1.Controllers
{

    [Authorize(Roles = "1,2,3")]
    public class StudentController : Controller
    {
        private Connection db = new Connection();


     
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult DoTitleExist(string title)
        {
            //
            bool isExist = db.Subjects.Where(u => u.Title.ToLowerInvariant().Equals(title.ToLower())).FirstOrDefault() != null;
            return Json(!isExist, JsonRequestBehavior.AllowGet);
        }


        [Route("opret-begreb")]
        public ActionResult Create()
        {
            ViewBag.SourceTypeID = new SelectList(db.SourceTypes, "SourceTypeID", "SourceTypeName");
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName");

            

            return View();
        }

        public JsonResult getSourceTypes(int id)
        {
           
            var sourceTypesCat = db.SourceTypeAttributes.Where(x => x.SourceTypeAttributeCatID == id).ToList();

            List<TextBox> liSourceTypesCat = new List<TextBox>();

            if (sourceTypesCat != null)
            {


                foreach (var x in sourceTypesCat)
                {

                    liSourceTypesCat.Add(new TextBox { Text = x.SourceTypeAttributeName, ID = x.SourceTypeAttributeID.ToString() });
                }
            }

            return Json(liSourceTypesCat, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult getSourceTypesInput(string getSourceTypeID, string getCourseTypeID)
        {



            return Json(new { success = true, message = "Order updated successfully" }, JsonRequestBehavior.AllowGet);
        }




        //Source sources,
        [Route("opret-begreb")]
        [HttpPost]
        public ActionResult Create(ConceptViewModel model, string getSourceTypeID, string getCourseTypeID)
        {
            
            ViewBag.CourseID = new SelectList(db.Courses).SelectedValue;
            ViewBag.SourceTypeID = new SelectList(db.SourceTypes).SelectedValue;

            int id;

            if (db.Concepts.Max(x => x.SourceID) == null)
            {
                id = 1;
            
            }

            else
            {
                id = db.Concepts.Max(x => x.SourceID).Value;

                id = id + 1;
            }
            
            if (ModelState.IsValid)
            {
              
                var concept = new Concept()
                {
                    Content = model.Content,
                    CourseID = Convert.ToInt32(getCourseTypeID),
                    SourceID = id

                };

                var subject = new Subject()
                {

                    Title = model.Title
                };



                var source = new Source()
                {
                    Arthor = model.Arthor,
                    SourceName = model.SourceName,
                    SourceTypeID = Convert.ToInt32(getSourceTypeID)

                };

                
                // In concept we have a ref called concept, thats is ref to subject
                concept.subject = subject;

                source.concept = concept;

                db.Concepts.Add(concept);

                db.Sources.Add(source);

                ViewBag.SourceTypeID = new SelectList(db.SourceTypes, "SourceTypeID", "SourceTypeID"); 
                ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName");

                db.SaveChanges();

            }


           
            return View();
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

           Subject subject = db.Subjects.Include(x => x.Concept).SingleOrDefault(x=> x.SubjectID == id);
            if (subject == null)
            {
                return HttpNotFound();
            }

            return View(subject);
        }

        [HttpPost]
        public ActionResult Edit(Subject model)
        {
     
            db.Database.ExecuteSqlCommand("UPDATE con SET con.Content = '" + model.Concept.Content +"' FROM Subjects AS  sub INNER JOIN Concepts AS con ON sub.SubjectID = con.ConceptID INNER JOIN Courses AS cou ON con.CourseID = cou.CourseID INNER JOIN Sources AS sou ON con.SourceID = sou.ConceptID WHERE sub.SubjectID = " + model.SubjectID);
            db.SaveChanges();


            return View(model);
        }





        }
}

concept-sharing-sem1/Controllers/UserController.cs
using concept_sharing_sem1.Models;
using concept_sharing_sem1.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Web.Mvc;

namespace concept_sharing_sem1.Controllers
{
    public class UserController : Controller
    {
        private Connection db = new Connection();
        // GET: User
        public ActionResult Create()
        {



            return View();
        }
        [HttpPost]
        public ActionResult Create(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new User()
                {
                    Username = model.Username,
                    Password = model.Password,
                    Email = model.Email,
                    RoleID = 3




                };

                db.Users.Add(user);
                db.SaveChanges();
                ModelState.Clear();
            }

            return View(model);

        }



    }
}

concept-sharing-sem1/Views/Shared/_Layout.cshtml
@using concept_sharing_sem1.Models;


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Concept sharing</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/css/sticky-footer-navbar.css" rel="stylesheet" />
    <link href="~/Content/custom.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Views/Search/conceptcss.css" rel="stylesheet" />

</head>
<body>

    <div class="navbar navbar-custom navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Concept sharing", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

           
       
                    <div class="col-sm-4 col-md-4">
                        <style>

                            .ui-autocomplete {
                                z-index: 2000 !important;
                                width:400px;
                            }

                        </style>
                
                        <form action="~/Search/Result" class="navbar-form" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" style="width:300px;"  id="txtCustomer" placeholder="Søg på begreber">
                                <input type="hidden" id="getSeachValue" name="ID" />
                                <div class="input-group-btn">
                                    <button class="btn btn-default" id="getSearchBTN" type="submit">Find begreb <i class="fa fa-search"></i></button>
                                </div>
                            </div>
                           @ViewBag.Error
                        </form>
                        
                    </div>

                
                <ul class="nav navbar-nav pull-right ">
                    <li>
                        @if (Request.IsAuthenticated)

    {
                    <a href="~/Student/Create" class="btn btn-success active"  role="button">Tilføj koncept</a>
                            
                        }
                    </li>
                  
                    <li>
          
                        @Html.ActionLink("Opret bruger", "Create", "User")
                    </li>

                    @if (User.Identity.IsAuthenticated)

                    {
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Min profil<span class="caret"></span></a>
                            <ul class="dropdown-menu">

                                <li>@Html.ActionLink("Min profil", "Role", "Auth")</li>
                          

                                @{

                                    using(Connection db = new Connection())
                                    {
                                        User user = new User();
                                        var getUserLoggedIn = User.Identity.Name;
                                        ViewBag.GetName = getUserLoggedIn;
                                        user = db.Users.FirstOrDefault(a => a.Email == getUserLoggedIn);
                                        if (user.RoleID == 1)
                                        {
                                            //Admin
                                            <li>

                                                   <li>@Html.ActionLink("Brugerliste", "Index", "Administrator")</li>
                                                   <li>@Html.ActionLink("Opret begreb", "Create", "Student")</li>

                                            </li>
                                        }
                                        else if (user.RoleID == 2)
                                        {
                                            <li>@Html.ActionLink("Se begreber", "Create", "Student")</li>
                                            //Teacher

                                        }

                                        else if (user.RoleID == 3)
                                        {
                                            <li>@Html.ActionLink("Opret begreb", "Create", "Student")</li>
                                            //Student

                                        }
                                    }



                                }


                            </ul>
</li>

                        <li>
                           
                            @Html.ActionLink("Log ud", "Logout", "Auth")
                        </li>
                    }

                    else
                    {
                        <li>
                            @Html.ActionLink("Log ind", "Logind", "Auth")
                        </li>

                    }
                </ul>
                
</div>
        </div>
    </div>
    <div style="bottom:0;">
        @RenderBody()


    </div>





           <script src="~/Scripts/jquery-3.2.1.js"></script>
        <script src="~/Scripts/bootstrap.js"></script>
        <script src="~/Scripts/bootstrap-tagsinput.js"></script>


        <!--Summernote-->
        <!-- include summernote css/js-->
        <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css" rel="stylesheet">
        <script src="~/Scripts/summernote.js"></script>
        <script src="~/Scripts/home-index.js"></script>

        <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
        <link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css" rel="stylesheet" />

        <script src="~/Scripts/Concept/searchConcept.js"></script>




</body>
</html>
    

concept-sharing-sem1/Views/Shared/_Login.cshtml
@model concept_sharing_sem1.Models.User

@using (Html.BeginForm(null, null, FormMethod.Post))
{
    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "E-mail adresse" } })
    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password", type = "password" } })

    <button type="submit">Log ind</button>

    @ViewBag.Error
}